# Generated by Django 4.1.1 on 2022-12-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArduinoServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donnee',
            name='Valeur',
            field=models.FloatField(),
        ),
    ]
