# Generated by Django 4.1.1 on 2022-12-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArduinoServer', '0002_alter_donnee_valeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='donnee',
            name='id_uc',
            field=models.IntegerField(default=0),
        ),
    ]
