# Generated by Django 4.1.1 on 2022-12-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArduinoServer', '0003_donnee_id_uc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donnee',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
