# Generated by Django 4.1.1 on 2022-12-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArduinoServer', '0004_alter_donnee_register_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donnee',
            name='id_uc',
        ),
        migrations.AddField(
            model_name='donnee',
            name='nom_capteur',
            field=models.CharField(default='', max_length=20),
        ),
    ]
