# Generated by Django 4.1.1 on 2022-12-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArduinoServer', '0005_remove_donnee_id_uc_donnee_nom_capteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('Valeur', models.FloatField()),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('nom_capteur', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
