# Generated by Django 4.1.5 on 2023-01-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entreprise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='Departement',
            field=models.CharField(default='Administration', max_length=70),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='ServiceOffert',
            field=models.CharField(default='Tutorat', max_length=70),
        ),
    ]
