# Generated by Django 4.1.1 on 2022-10-05 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='enseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ecole.enseignant'),
        ),
    ]
